In [1]:
import os
import tempfile
import zipfile
from pathlib import Path

import geopandas as gpd
import pandas as pd
import sqlalchemy
from dbfread import DBF

In [2]:
engine = sqlalchemy.create_engine(
    f"postgresql+psycopg2://{os.environ['POSTGRES_USER']}:{os.environ['POSTGRES_PASSWORD']}@{os.environ['POSTGRES_HOST']}:{os.environ['POSTGRES_PORT']}/{os.environ['POSTGRES_DB']}"
)

In [6]:
dbf = DBF(
    "/home/lain/Documents/censo2000_scince/Scince 2000 Aguascalientes/Data/F43625_CGPV2000.DBF"
)
df = (
    pd.DataFrame(iter(dbf))
    .reset_index()
    .assign(index=lambda df: df["index"] + 1)
    .set_index("index")
)
df

                                           NOMBRES DESCRIBE
index
1                                  Población total
2                              Población masculina
3                               Población femenina
4                          Población de 0 a 4 años
5                Población masculina de 0 a 4 años
...                                            ...      ...
166                 Hogares con jefatura masculina
167                  Hogares con jefatura femenina
168                           Población en hogares
169    Población en hogares con jefatura masculina
170     Población en hogares con jefatura femenina

[170 rows x 2 columns]

In [3]:
data_path = Path("./data")
input_path = data_path / "input"

In [17]:
state_code = "01"
fpath = input_path / "2010" / "scince" / f"{state_code}_SCINCE_zip.zip"
with zipfile.ZipFile(fpath) as zf, tempfile.TemporaryDirectory() as tmpdir:
    zf.extractall(tmpdir)
    data_path = Path(tmpdir) / state_code

    df = gpd.read_file(data_path / "ageb_urb.shp")

    dbf = DBF(data_path / "descriptores" / "desc_cpv2010.DBF", encoding="latin-1")
    desc = pd.DataFrame(iter(dbf))

In [5]:
dbf = DBF("app/01_AGS/descriptores/desc_cpv2020.dbf", encoding="latin1")
df = pd.DataFrame(iter(dbf))
df

        CAMPO                              DESCRIP
0        POB1                      Población total
1        POB2              Población de 0 a 2 años
2        POB3              Población de 0 a 4 años
3        POB4              Población de 3 a 5 años
4        POB5             Población de 6 a 11 años
..        ...                                  ...
846      TIPO  Clasificación del objeto geográfico
847  CVE_SERV                   Clave del servicio
848    AMBITO                  Ámbito del servicio
849   CVEGEO1                 Clave geoestadística
850   CVESERV                   Clave del servicio

[851 rows x 2 columns]

In [6]:
df

        CAMPO                              DESCRIP
0        POB1                      Población total
1        POB2              Población de 0 a 2 años
2        POB3              Población de 0 a 4 años
3        POB4              Población de 3 a 5 años
4        POB5             Población de 6 a 11 años
..        ...                                  ...
846      TIPO  Clasificación del objeto geográfico
847  CVE_SERV                   Clave del servicio
848    AMBITO                  Ámbito del servicio
849   CVEGEO1                 Clave geoestadística
850   CVESERV                   Clave del servicio

[851 rows x 2 columns]

In [ ]:
with engine.connect() as conn:
    gdf = gpd.read_postgis(
        """
        SELECT cvegeo, pobtot, geometry FROM census_2020_ageb
        WHERE cvegeo = '010060001009A'
        """,
        con=conn,
        geom_col="geometry",
    )

In [8]:
gdf

          cvegeo  pobtot                                           geometry
0  010060001009A    2940  POLYGON ((2471856.117 1124829.239, 2471859.442...